# Generated by Django 3.2.25 on 2025-06-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('material', models.CharField(max_length=100)),
                ('finish', models.CharField(max_length=100)),
                ('images', models.JSONField()),
                ('qty_in_stock', models.PositiveIntegerField()),
            ],
        ),
    ]
