# Generated by Django 4.2.19 on 2025-07-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
