# Generated by Django 4.2.19 on 2025-08-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketitem',
            name='reserved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basketitem',
            name='reserved_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
