# Generated by Django 4.2.19 on 2025-08-05 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_basketitem_reserved_at_basketitem_reserved_until'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basketitem',
            old_name='reserved_at',
            new_name='added_to_basket_at',
        ),
        migrations.RenameField(
            model_name='basketitem',
            old_name='reserved_until',
            new_name='remain_in_basket_until',
        ),
    ]
